spring.config.import=application-common-dev.properties

#messaging consumer properties
messaging.consumer.request.max-size=1
messaging.consumer.request.auto-start=true
messaging.queue.request.problem=ma-example-request-problem-queue
external.usersBaseUrl=https://jsonplaceholder.typicode.com

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

messaging.queue.request=ma-example-request-queue
messaging.queue.result=ma-example-result-queue
messaging.queue.result.problem=ma-example-result-problem-queue
spring.rabbitmq.virtual-host=/
